### ISSUE TITLE
getting compiler error from Python2.7 subprocessor.py

### ISSUE THREAD

**Issue by EduardoRenani** [duff2013/ulptool#54]
OS: macOS Catalina. ESP32 version 1.0.4 installed by Board Manager. Error message:

Traceback (most recent call last):
  File "/Users/eduardoribeiro/Library/Arduino15/packages/esp32/tools/ulptool/src/esp32ulp_build_recipe.py", line 560, in <module>
    main(sys.argv[1:])
  File "/Users/eduardoribeiro/Library/Arduino15/packages/esp32/tools/ulptool/src/esp32ulp_build_recipe.py", line 106, in main
    build_ulp(PATHS, ulp_files, board_options, True)
  File "/Users/eduardoribeiro/Library/Arduino15/packages/esp32/tools/ulptool/src/esp32ulp_build_recipe.py", line 137, in build_ulp
    proc = subprocess.Popen(cmd[1],stdout=subprocess.PIPE,stderr=subprocess.PIPE,shell=False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by duff2013** [comment]
Hmmm, don't have Catalina on any machines but I know Apple locked down a lot of stuff I wonder if python subsystem calls are a part of that?

**Comment by duff2013** [comment]
Are you the Admin of this computer? Can you check the folder ../esp32ulp-elf-binutils/bin/ folder permissions for all the binutils executables?

**Comment by EduardoRenani** [comment]
Hey Duff, thanks for the fast reply. I made it work by giving permission for every file inside “../esp32ulp-elf-binutils/bin/” and creating a python virtual environment for Arduino.
